name: Bale Bot Runner

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 360

    env:
      BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
      BALE_CHAT_ID: ${{ secrets.BALE_CHAT_ID }}
      ENABLE_TELEGRAM: "true"

    steps:
      - uses: actions/checkout@v4

      - name: Clone downloader
        run: |
          git clone https://github.com/mariosemes/PornHub-downloader-python.git PornHub-downloader-python-master

      - name: Fix old lxml
        run: |
          sed -i 's/lxml==4.6.3/lxml==4.9.3/g' PornHub-downloader-python-master/requirements.txt

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r PornHub-downloader-python-master/requirements.txt

      - name: Run bot
        run: |
          timeout 5h python bot.py
